### ISSUE TITLE
Access denied due to invalid VCC-API-KEY

### ISSUE THREAD

**Issue by grzegorztomasiak** [volvo-cars/developer-portal-api-samples#8]
I've created app under developer account and copied VCC API key - Primary but there's still an error 

`{
    "status": 401,
    "error": {
        "message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application."
    }
}`

The app isn't publish since it was made for testing purposes but the API does not want to accept the VCC API, any ideas?

**Comment by adamgronberg** [comment]
Hi @grzegorztomasiak. Thanks for raising an issue :raised_hands: 

To better help you, we require some more information.

How are you running the request? Are you trying to run our samples in this repo?
Have you verified that the VCC_API_KEY is correctly added to the .env file?

If you still have issues, please try to execute a simple curl command following the instructions here:
https://developer.volvocars.com/apis/docs/getting-started/

**Comment by thiemo-seys** [comment]
Hi @adamgronberg, I have the exact same issue when trying out the connected-vehicle-fetch-sample.

This also happens when I try to execute the request in curl/python.

Could this be because my application is not published?
Status: Only for testing

**Comment by markhaines** [comment]
I'm having same issue. Have tried creating multiple 'apps' and regenerating the keys etc.

**Comment by REELcoder** [comment]
Same for me. Happens even in the sandbox>
![image](https://github.com/volvo-cars/developer-portal-api-samples/assets/16427391/705ca3ee-6aea-4e65-b7dc-361d83bbe248)

**Comment by Isshin** [comment]
Same here... tried multiple applications and regenerated multiple times

**Comment by adamgronberg** [comment]
Hi all, thanks for the added context.

It looks like the issues are related to the API, and not related to the sample code in this repository.
I've escalated this internally. You can also contact developer.portal@volvocars.com for more direct help.

I will leave this issue open until we've fully investigated the reason for the errors.

**Comment by DuncanSmith** [comment]
Same error here. I've never managed to get it to work at all in either command line curl or a programming environment, e.g. these node packages. I've tried regenerating my VCC API keys but makes no difference, same 401 error. Looks like something is borked in the API system/auth itself. 
If helpful, here is my -vvvv curl output. 
`
curl -vvvv 'https://api.volvocars.com/connected-vehicle/v2/vehicles' \
| => -H 'accept: "application/json"' \
| => -H 'authorization: Bearer my-bearer-token' \
| => -H 'vcc-api-key: my-vcc-api-key'
*   Trying 52.19.178.68:443...
* Connected to api.volvocars.com (52.19.178.68) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: C=SE; L=Gothenburg; O=Volvo Car Corporation; CN=api.volvocars.com
*  start date: Feb 15 00:00:00 2023 GMT
*  expire date: Mar  6 23:59:59 2024 GMT
*  subjectAltName: host "api.volvocars.com" matched cert's "api.volvocars.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://api.volvocars.com/connected-vehicle/v2/vehicles
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: api.volvocars.com]
* [HTTP/2] [1] [:path: /connected-vehicle/v2/vehicles]
* [HTTP/2] [1] [user-agent: curl/8.4.0]
* [HTTP/2] [1] [accept: "application/json"]
* [HTTP/2] [1] [authorization: Bearer my-bearer-token]
* [HTTP/2] [1] [vcc-api-key: my-vcc-api-key]
> GET /connected-vehicle/v2/vehicles HTTP/2
> Host: api.volvocars.com
> User-Agent: curl/8.4.0
> accept: "application/json"
> authorization: Bearer my-bearer-token
> vcc-api-key: my-vcc-api-key
>
< HTTP/2 401
< content-length: 270
< content-type: application/json
< date: Sun, 28 Jan 2024 19:40:15 GMT
< server: vcc
< access-control-allow-origin: https://developer.volvocars.com
< request-context: appId=cid-v1:d08a6ac1-4942-4ce7-a466-f3dd07fd71d1
<
{
                        "status": 401,
                        "error": {
                            "message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application."
                        }
* Connection #0 to host api.volvocars.com left intact
                    }
`

**Comment by DuncanSmith** [comment]
Have also tried accessing this via [VolvoMQTT](https://github.com/Dielee/volvo2mqtt) Home Assistant integration but same error message of:

`Feb 01 22:43:16 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.8.27

Feb 01 22:43:17 volvo2mqtt [106] - WARNING: VCCAPIKEY <masked> isn't working! Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application.

Feb 01 22:43:17 volvo2mqtt [106] - WARNING: No working VCCAPIKEY found, waiting 10 minutes. Then trying again!`

Any idea when this will be addressed?

**Comment by Michel-NL** [comment]
> Have also tried accessing this via [VolvoMQTT](https://github.com/Dielee/volvo2mqtt) Home Assistant integration but same error message of:
> 
> `Feb 01 22:43:16 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.8.27
> 
> Feb 01 22:43:17 volvo2mqtt [106] - WARNING: VCCAPIKEY isn't working! Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application.
> 
> Feb 01 22:43:17 volvo2mqtt [106] - WARNING: No working VCCAPIKEY found, waiting 10 minutes. Then trying again!`
> 
> Any idea when this will be addressed?

Did you try the portal? https://developer.volvocars.com/apis/connected-vehicle/v2/specification/#openapi
I noticed this week that it is working a little bit better. It still comes up some times with an 401, but pressing the execute button again and then it works. 
It works 3 out of 5 times for the first try.

**Comment by DuncanSmith** [comment]
Thanks @Michel-NL , I did try via the portal too but I have a very low success rate on good responses. Actually, I don't think I've had a valid response from the portal, only ones from MQTT via Home Assistant. To be frank, I don't have time to keep pressing a button to get a valid response, Volvo really need to get the stability of the API corrected!
For info, here's the tail of the HA log file so far - just full of auth errors!
`
Feb 02 12:40:33 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:40:33 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:40:33 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:40:33 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds. 
Feb 02 12:45:33 volvo2mqtt [106] - INFO: Sending mqtt update... 
Feb 02 12:45:33 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:45:33 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:45:33 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:45:33 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:45:33 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:45:33 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:45:33 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds. 
Feb 02 12:50:33 volvo2mqtt [106] - INFO: Sending mqtt update... 
Feb 02 12:50:34 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:50:34 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:50:34 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:50:34 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:50:34 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:50:34 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 401. Error: {"status": 401, "error": {"message": "Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application." } } 
Feb 02 12:50:34 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
`

**Comment by adamgronberg** [comment]
Hello everyone, and thank you for your continued error reports. I've forwarded all your comments to the support team.

However, since the errors you are encountering are not related to the code in this repository, we've determined that we will have to close this issue.

For further assistance and error reporting, please continue to reach out to the Volvo Cars' Developer Portal support at [developer.portal@volvocars.com](mailto:developer.portal@volvocars.com). They are better equipped to assist with your issues.
